services:
  parsedmarc:
    build: ./parsedmarc
    volumes:
      - ./input_files:/input:ro
      - ./output_files:/output
      - ./parsedmarc/parsedmarc.ini:/parsedmarc.ini
    command: parsedmarc -c /parsedmarc.ini /input/*
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  grafana:
    build: ./grafana
    ports:
      - 3000:3000
